AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Cybereason Sensor
Parameters:
  AVTagName:
    Default: Antivirus
    Type: String
    Description: Tag name of the target EC2 instances
  AVTagValues:
    Default: 'yes'
    Type: CommaDelimitedList
    Description: Tags values of the target EC2 instances
  LogBucketName:
    Type: String
    Description: Bucket name for association's logs
  LogBucketPrefix:
    Type: String
    Description: Bucket prefix for association's logs
Conditions:
  CreateS3Bucket: !Equals [ !Ref LogBucketName, '' ]
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Antivirus
        Parameters:
          - AVTagName
          - AVTagValues
      -
        Label:
          default: Logging
        Parameters:
          - LogBucketName
          - LogBucketPrefix
    ParameterLabels:
      AVTagName:
        default: Name of the tag used to deploy the antivirus
      AVTagValues:
        default: Value(s) used to deploy the antivirus
      LogBucketName:
        default: Name of an existing bucket that you want to use or leave blank to create a new bucket
      LogBucketPrefix:
        default: Prefix of the bucket
Resources:
  LoggingBucket:
    Type: AWS::S3::Bucket
    Condition: CreateS3Bucket
    Properties:
      LifecycleConfiguration:
        Rules: 
        - ExpirationInDays: 90
          Status: Enabled
  LoggingBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateS3Bucket
    Properties:
      Bucket: 
        Ref: LoggingBucket
      PolicyDocument:
        Statement:
        - Effect: Allow
          Action:
          - s3:GetBucketLocation
          - s3:PutObject
          - s3:GetObject
          - s3:GetEncryptionConfiguration
          - s3:AbortMultipartUpload
          - s3:ListMultipartUploadParts
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          Resource:
          - !GetAtt LoggingBucket.Arn
          - !Sub ${LoggingBucket.Arn}/*
          Principal:
            AWS: '*'
          Condition:
            ArnLike:
              aws:PrincipalArn: "arn:aws:iam::${AWS::AccountId}:role/*"
  CybereasonDocument:
    Type: AWS::SSM::Document
    Properties:
      DocumentType: Command
      Content:
        description: Install Cybereason Sensor
        schemaVersion: '2.2'
        mainSteps:
        - action: aws:runPowerShellScript
          name: uninstallWindowsDefenderAndReboot
          precondition:
            StringEquals:
            - platformType
            - Windows
          inputs:
            runCommand:
            - |
                $ErrorActionPreference = "Stop"
                $defender = Get-WindowsFeature -Name "Windows-Defender"
                if($defender.Installed){
                  $defender | Uninstall-WindowsFeature
                  # https://docs.aws.amazon.com/systems-manager/latest/userguide/send-commands-reboot.html
                  exit 3010
                }
        - action: aws:runPowerShellScript
          name: installCybereasonSensorWindows
          precondition:
            StringEquals:
            - platformType
            - Windows
          inputs:
            runCommand:
            - |
                $ErrorActionPreference = "Stop"
                if(-not (Get-WmiObject Win32_Product -Filter "Name='Cybereason Sensor'")){
                  $folder=Join-Path ([System.IO.Path]::GetTempPath()) 'CybereasonInstall'
                  Copy-S3Object -BucketName 'cybereasonsensor' -KeyPrefix '/Windows/' -LocalFolder $folder
                  Start-Process (Join-Path $folder 'CybereasonSensor64_18_1_111_0_tamedia_tamedia-r.cybereason.net_443_ACTIVE_NORMAL_OfflineInstall.exe') -ArgumentList '/install','/norestart','/quiet','-l C:\Windows\Temp\CybereasonInstall.log','AP_APP_CTRL=1','ANTI_MALWARE=1','AP_AV_MODE=3','AP_SA_DETECT_MODE=3','AP_SA_PREVENT_MODE=1','AP_STATE=ACTIVE_NORMAL' -Wait
                  Remove-Item $folder -Force -Recurse
                }
        - action: aws:runShellScript
          name: installCybereasonSensorLinux
          precondition:
            StringEquals:
            - platformType
            - Linux
          inputs:
            runCommand:
            - |
                #!/bin/bash
                set -e
                if ! rpm -qi cybereason-sensor --quiet; then
                  agentPath='/tmp/cybereasonInstall'
                  aws s3 cp s3://cybereasonsensor/Linux/ $agentPath --recursive
                  rpm -ihv $agentPath/cybereason-sensor-18.1.111.0-1.x86_64_tamedia_tamedia-r.cybereason.net_443_ACTIVE_NORMAL_rpm.rpm
                  rm -rf $agentPath
                fi
  CybereasonDocumentAssociation:
    Type: AWS::SSM::Association
    Properties:
      OutputLocation:
        S3Location:
          OutputS3BucketName:
            !If
            - CreateS3Bucket
            - !Ref LoggingBucket
            - !Ref LogBucketName
          OutputS3KeyPrefix: !Ref LogBucketPrefix
      ScheduleExpression: rate(2 hours)
      Name: !Ref CybereasonDocument
      Targets:
      - Key: !Sub tag:${AVTagName}
        Values: !Ref AVTagValues